// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Fe2igJUVhU2aTcJMYPYOYntdSzxcXPA',
    appId: '1:114024480973:web:d6b8b85aa3d572a1d3a984',
    messagingSenderId: '114024480973',
    projectId: 'notepad-8e941',
    authDomain: 'notepad-8e941.firebaseapp.com',
    storageBucket: 'notepad-8e941.firebasestorage.app',
    measurementId: 'G-D6G2JW29JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCZ5L5Rmhqe6dTJv808mSbcfQysmwr5A8',
    appId: '1:114024480973:android:7f284dcb1787cab1d3a984',
    messagingSenderId: '114024480973',
    projectId: 'notepad-8e941',
    storageBucket: 'notepad-8e941.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Fe2igJUVhU2aTcJMYPYOYntdSzxcXPA',
    appId: '1:114024480973:web:59e046c73015acc4d3a984',
    messagingSenderId: '114024480973',
    projectId: 'notepad-8e941',
    authDomain: 'notepad-8e941.firebaseapp.com',
    storageBucket: 'notepad-8e941.firebasestorage.app',
    measurementId: 'G-B7QX6ZNQ9W',
  );
}
